version: 0.4.1.{build}
image: Visual Studio 2015
configuration: Release
before_build:
  - nuget restore src
test:
  assemblies:
    only:
      - FakeHttpContext.Tests.dll
after_test:
  - ps: '& ".\pack.ps1"'
artifacts:
  - path: 'output\*.nupkg'