version: 0.4.1.{build}
image: Visual Studio 2015
configuration: Release
before_build:
  - nuget restore src
test:
  assemblies:
    only:
      - FakeHttpContext.Tests.dll
after_test:
  - ps: '& ".\pack.ps1"'
artifacts:
  - path: 'output\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: 6RCAME9ubTeKvj1cSeybJohOkgHSakCyRy3pHgxbUm0LBAZRbncRz01pKoc0mcK1
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/
    release: $(appveyor_repo_tag_name)
    draft: true
    prerelease: false
    auth_token:
        secure: c88+SkzG9YaQKGJSC1HwE1xkxzkMQ/Z0HquvWU08KEIWK7WceksndLmKoIxpsQu+
    on:
      branch: master
      appveyor_repo_tag: true